var a = $false
try {
	throw new Exception()
} catch($e : Exception) {
	$a = $true
}
assert($a)

try {
	throw new NotPermittedException()
} catch($e : DerivedFromErrnoException) {
	assert($e.getErrno() == "EACCES")
}